---
- name: create instances
  hosts: localhost
  roles:
    - create_instances

- name: update cache
  hosts: spark, hdfs
  become: yes
  roles:
    - update_cache

- name: install spark
  hosts: spark
  become: yes
  roles:
    - azavea.spark

- name: install hdfs
  hosts: hdfs
  become: yes
  roles:
    - azavea.hdfs
