---
- name: launch instances
  os_server:
    name: "{{ prefix }}--{{ item.name }}"
    state: present
    image: "{{ item.image }}"
    key_name: "{{ item.key }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    security_groups: default
  with_items: "{{ servers }}"
  register: "os_hosts"

- name: add hosts to inventory
  add_host:
    name: "{{ item['openstack']['human_id'] }}"
    groups: "{{ item['item']['meta']['group'] }}"
    ansible_host: "{{ item.openstack.accessIPv4 }}"
    ansible_ssh_user: ubuntu
  with_items: "{{ os_hosts.results }}"

- name: wait for instance launch
  wait_for:
    port: 22
    delay: 5
    timeout: 600
    host: "{{ item.openstack.accessIPv4 }}"
  with_items: "{{ os_hosts.results }}"
